### ISSUE TITLE
Move to testing with pycodestyle instead of pep8

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/CarbonDate#20]
[Guido recommended](https://github.com/PyCQA/pycodestyle/issues/466) not using pep8 to describe the module to test for PEP8 compliance. Testing using the pep8 module ought to be move to use [pycodestyle](https://github.com/PyCQA/pycodestyle) instead. Supposedly the package is feature-equivalent with pep8 but that is not longer true per [my experience](https://github.com/oduwsdl/ipwb/issues/279). Additional tests may have been added to pep8/pycodestyle to be stricter to the PEP8 style guide.

**Comment by grantat** [comment]
Some Travis build ouput:
```
pep8 has been renamed to pycodestyle (GitHub issue #466)
Use of the pep8 tool will be removed in a future release.
Please install and use `pycodestyle` instead.
```
So I suppose switching over is a good idea at this point. I'm also getting E722 in a few files:
```
(venv) Grants-MBP:CarbonDate gatkins$ pycodestyle --ignore=E501 main.py ./modules/
./modules/cdGetArchives.py:139:5: E722 do not use bare except'
./modules/cdGetBacklinks.py:37:5: E722 do not use bare except'
./modules/cdGetBacklinks.py:66:5: E722 do not use bare except'
./modules/cdGetBing.py:29:5: E722 do not use bare except'
./modules/cdGetBitly.py:30:5: E722 do not use bare except'
./modules/cdGetBitly.py:59:9: E722 do not use bare except'
./modules/cdGetBitly.py:129:5: E722 do not use bare except'
./modules/cdGetFirstAppearanceInArchives.py:25:5: E722 do not use bare except'
./modules/cdGetFirstAppearanceInArchives.py:110:5: E722 do not use bare except'
./modules/cdGetGoogle.py:99:9: E722 do not use bare except'
./modules/cdGetLowest.py:45:9: E722 do not use bare except'
./modules/cdGetLowest.py:83:9: E722 do not use bare except'
./modules/cdGetPubdate.py:18:5: E722 do not use bare except'
```

**Comment by hugovk** [comment]
The `pep8` tool was renamed to `pycodestyle`, and development continues as `pycodestyle`. 

So running `pep8` is essentially the same as running an old version of `pycodestyle`.
